// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD6qQWRZYXsGKoMCwG1fZHqAqTDA83bsCg',
    appId: '1:752821000317:web:933a7213edc8923b3fb914',
    messagingSenderId: '752821000317',
    projectId: 'bookstore-e7a3d',
    authDomain: 'bookstore-e7a3d.firebaseapp.com',
    storageBucket: 'bookstore-e7a3d.firebasestorage.app',
    measurementId: 'G-84C0VYWL5H',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD6vZXllN_b-TJPeJFnKMZncb9x-hZPGww',
    appId: '1:752821000317:android:c01d85f5ee629e4e3fb914',
    messagingSenderId: '752821000317',
    projectId: 'bookstore-e7a3d',
    storageBucket: 'bookstore-e7a3d.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDhjMA8T25-4l9weKaFlGpP-GlXpPv9OMg',
    appId: '1:752821000317:ios:7c350a1881488b613fb914',
    messagingSenderId: '752821000317',
    projectId: 'bookstore-e7a3d',
    storageBucket: 'bookstore-e7a3d.firebasestorage.app',
    iosClientId: '752821000317-7irb77ms187kdihl6e7khhgl35jj1cd3.apps.googleusercontent.com',
    iosBundleId: 'com.example.bookstoreApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDhjMA8T25-4l9weKaFlGpP-GlXpPv9OMg',
    appId: '1:752821000317:ios:7c350a1881488b613fb914',
    messagingSenderId: '752821000317',
    projectId: 'bookstore-e7a3d',
    storageBucket: 'bookstore-e7a3d.firebasestorage.app',
    iosClientId: '752821000317-7irb77ms187kdihl6e7khhgl35jj1cd3.apps.googleusercontent.com',
    iosBundleId: 'com.example.bookstoreApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD6qQWRZYXsGKoMCwG1fZHqAqTDA83bsCg',
    appId: '1:752821000317:web:474ce0649e43c8e03fb914',
    messagingSenderId: '752821000317',
    projectId: 'bookstore-e7a3d',
    authDomain: 'bookstore-e7a3d.firebaseapp.com',
    storageBucket: 'bookstore-e7a3d.firebasestorage.app',
    measurementId: 'G-MB6S5HNXF5',
  );
}
